/*
	Auto-generated by ../../tools/noi2h.py
	Source: out/common.noi
*/

#define common_lcd_delay_long_addr 0x1000
#define common_lcd_delay_short_addr 0x100c
#define common_lcd_writeControl_addr 0x1018
#define common_lcd_writeData_addr 0x1028
#define common_lcd_set_cursor_addr 0x1035
#define common_lcd_map_4rows_addr 0x1065
#define common_lcd_clear_addr 0x10b6
#define common_lcd_refresh_addr 0x10e7
#define common_lcd_scroll_addr 0x1125
#define common_lcd_init_addr 0x1149
#define common_lcd_putchar_addr 0x118f
#define common_port_0x10_in_addr 0x1245
#define common_port_0x10_out_addr 0x124c
#define common_port_0x11_in_addr 0x1254
#define common_port_0x11_out_addr 0x125b
#define common_port_0x12_in_addr 0x1263
#define common_port_0x12_out_addr 0x126a
#define common_vgl_shutdown_addr 0x1272
#define common_keyboard_inkey_addr 0x127c
#define common_vgl_key_map_addr 0x12ef
#define common_keyboard_checkkey_addr 0x132f
#define common_keyboard_getchar_addr 0x1352
#define common_vgl_sound_off_addr 0x136e
#define common_vgl_sound_addr 0x1376
#define common_vgl_sound_note_addr 0x13b8
#define common_beep_addr 0x1488
#define common_vgldk_init_addr 0x1496
#define common_printf_addr 0x14a3
#define common_printf_d_addr 0x14b5
#define common_gets_addr 0x14f2
#define common_strlen_addr 0x1557
#define common_memcpy_addr 0x1567
#define common_memset_addr 0x15a1
#define common_main_addr 0x15b9
#define common_bank1_call_addr 0x15ce
#define common_lcd_buffer_addr 0xc800
#define common_lcd_scroll_cb_addr 0xc850
#define common_lcd_x_addr 0xc852
#define common_lcd_y_addr 0xc853
#define common_lcd_cursor_addr 0xc854
#define common_keyboard_getchar_last_addr 0xc855
