
NAME = hello

# For targeting a specific model:
#VGLDK_SERIES = 1000
#VGLDK_SERIES = 2000
#VGLDK_SERIES = 4000
VGLDK_SERIES = 6000

# For small loadable apps (without their own I/O):
#VGLDK_SERIES = 0
#LOC_CODE = 0xc800
#LOC_DATA = 0xc100

include ../../tools/Makefile.mk

#all: cart
#all: emu
