
#NAME = raycast.naive
#NAME = raycast.olc1
#NAME = raycast.olc2
NAME = raycast.mahnke


# For targeting a specific model:
#VGLDK_SERIES = 1000
#VGLDK_SERIES = 2000
#VGLDK_SERIES = 4000
VGLDK_SERIES = 6000

# For small loadable apps (without their own I/O):
#VGLDK_SERIES = 0
#LOC_CODE = 0xc800
#LOC_DATA = 0xc000

# If you need some more...
CART_SIZE_KB=16

all: cart
#all: app
#all: emu
#all: burn

include ../../tools/Makefile.mk
