
NAME = raycast

# For targeting a specific model:
#VGLDK_SERIES = 1000
#VGLDK_SERIES = 2000
#VGLDK_SERIES = 4000
VGLDK_SERIES = 6000

# For small loadable apps (without their own I/O):
#VGLDK_SERIES = 0
#LOC_CODE = 0xc800
#LOC_DATA = 0xc100

all: cart
#all: app
#all: emu
#all: burn

include ../../tools/Makefile.mk
