/*
	A crappy ass raycaster
	- no rotations
	- no perspective
	- no trigonometry
	- no perspective correction
	
	2020-07-07 Bernhard "HotKey" Slawik
*/

#define TEXT_MODE
//#define GFX_MODE


#define lcd_MINIMAL	// Use minimal text mode (no scrolling)
#include <vgldk.h>
#include <stdiomin.h>

#define FOV (SINTABLE_SIZE / 4)
#define OVERSAMPLE 2
#define SPEED_TURN 10
#define SPEED_MOVE 2



// Auto-generated by sintable.py
#define SINTABLE_INDEX_TYPE unsigned char
#define SINTABLE_SIZE 256
#define SINTABLE_VALUE_TYPE signed char
#define SINTABLE_SCALE 127
const signed char SINTABLE[256] = {
	   0,    3,    6,    9,   12,   16,   19,   22,   25,   28,   31,   34,   37,   40,   43,   46,   49,   51,   54,   57,   60,   63,   65,   68,   71,   73,   76,   78,   81,   83,   85,   88,
	  90,   92,   94,   96,   98,  100,  102,  104,  106,  107,  109,  111,  112,  113,  115,  116,  117,  118,  120,  121,  122,  122,  123,  124,  125,  125,  126,  126,  126,  127,  127,  127,
	 127,  127,  127,  127,  126,  126,  126,  125,  125,  124,  123,  122,  122,  121,  120,  118,  117,  116,  115,  113,  112,  111,  109,  107,  106,  104,  102,  100,   98,   96,   94,   92,
	  90,   88,   85,   83,   81,   78,   76,   73,   71,   68,   65,   63,   60,   57,   54,   51,   49,   46,   43,   40,   37,   34,   31,   28,   25,   22,   19,   16,   12,    9,    6,    3,
	   0,   -3,   -6,   -9,  -12,  -16,  -19,  -22,  -25,  -28,  -31,  -34,  -37,  -40,  -43,  -46,  -49,  -51,  -54,  -57,  -60,  -63,  -65,  -68,  -71,  -73,  -76,  -78,  -81,  -83,  -85,  -88,
	 -90,  -92,  -94,  -96,  -98, -100, -102, -104, -106, -107, -109, -111, -112, -113, -115, -116, -117, -118, -120, -121, -122, -122, -123, -124, -125, -125, -126, -126, -126, -127, -127, -127,
	-127, -127, -127, -127, -126, -126, -126, -125, -125, -124, -123, -122, -122, -121, -120, -118, -117, -116, -115, -113, -112, -111, -109, -107, -106, -104, -102, -100,  -98,  -96,  -94,  -92,
	 -90,  -88,  -85,  -83,  -81,  -78,  -76,  -73,  -71,  -68,  -65,  -63,  -60,  -57,  -54,  -51,  -49,  -46,  -43,  -40,  -37,  -34,  -31,  -28,  -25,  -22,  -19,  -16,  -12,   -9,   -6,   -3
};
SINTABLE_VALUE_TYPE sin(SINTABLE_INDEX_TYPE a) {
	return SINTABLE[a];
}
SINTABLE_VALUE_TYPE cos(SINTABLE_INDEX_TYPE a) {
	return SINTABLE[a + (SINTABLE_SIZE/4)];
}


// Map
#define LEVEL_W 16
#define LEVEL_H 16
const char LEVEL[LEVEL_W][LEVEL_H] = {
	{'x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ','x',' ',' ',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ','x',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ','x',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ','x',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ','x',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ','x',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ','x',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','x'},
	{'x',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','x'},
	{'x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x'},
};


#ifdef TEXT_MODE
	#define SCREEN_W LCD_COLS
	#define SCREEN_H LCD_ROWS
	/*
	void lcd_putchar_at(int x, int y, char c) {
		lcd_x = x;
		lcd_y = y;
		lcd_putchar(c);
	}
*/
	
	#define MAX_DEPTH 9
	const char COL_PATTERNS[MAX_DEPTH][SCREEN_H] = {
		{
			'X',
			'X',
			'X',
			'X',
		},
		{
			'-',
			' ',
			' ',
			' ',
		},
		{
			'_',
			' ',
			' ',
			'_',
		},
		{
			' ',
			'-',
			' ',
			'-',
		},
		{
			' ',
			'_',
			'_',
			':',
		},
		{
			' ',
			' ',
			'=',
			':',
		},
		{
			' ',
			' ',
			'-',
			':',
		},
		{
			' ',
			' ',
			'.',
			':',
		},
		{
			' ',
			' ',
			' ',
			':',
		},
	};


void drawCol(int x, int z, char b) {
	int y;
	
	if ((b == ' ') || (z > MAX_DEPTH-1)) z = MAX_DEPTH-1;	// z clip
	
	(void)b;	// Current block character
	
	for(y = 0; y < SCREEN_H; y++) {
		lcd_putchar_at(x, y, COL_PATTERNS[z][y]);
	}
	
}
#endif

#ifdef GFX_MODE
	//#define SCREEN_W 240
	#define SCREEN_W 30
	#define SCREEN_H 100
	#define MAX_DEPTH 16
void drawVLine(int x, int y1, int h) {
	byte *p;
	int y;
	
	for(y = y1; y < y1+h; y++) {
		//p = (byte *)lcd_addr + (y * lcd_w + x) / 8;
		p = (byte *)lcd_addr + (y * lcd_w/8 + x);
		*p = 0xff;
	}
}

void drawCol(int x, int z, char b) {
	
	if (z > MAX_DEPTH-1) z = MAX_DEPTH-1;	// z clip
	
	(void)b;	// Current block character
	
	//drawVLine(x, SCREEN_H/2 - z*2, z*4);
	drawVLine(x, z * (SCREEN_H / (MAX_DEPTH*2)), SCREEN_H - z * (SCREEN_H / MAX_DEPTH));
	
}
#endif

int player_x = LEVEL_W/2;
int player_z = LEVEL_H/2;
int player_a = 0;


void drawScreen() {
	int ix;
	int iz;
	
	int a;
	int dx;
	int dz;
	
	int x;
	int z;
	char b;
	
	lcd_clear();
	
	for(ix = 0; ix < SCREEN_W; ix++) {
		a = player_a -(FOV/2) + (ix * FOV / (SCREEN_W-1));
		
		dx = sin((a + SINTABLE_SIZE) % SINTABLE_SIZE);
		dz = sin((a + SINTABLE_SIZE + SINTABLE_SIZE/4) % SINTABLE_SIZE);
		
		// Naive: Go linear
		//dx = OVERSAMPLE * -(FOV / 2) + (OVERSAMPLE * FOV * ix) / (SCREEN_W-1);
		//dz = OVERSAMPLE * -MAX_DEPTH;
		//hit = false;
		
		b = '?';
		for(iz = 0; iz < MAX_DEPTH; iz++) {
			x = (player_x + (dx * iz * OVERSAMPLE) / SINTABLE_SCALE) / OVERSAMPLE;
			z = (player_z + (dz * iz * OVERSAMPLE) / SINTABLE_SCALE) / OVERSAMPLE;
			if ((x < 0) || (x >= LEVEL_W)) {
				b = '1';
				break;
			}
			if ((z < 0) || (z >= LEVEL_H)) {
				b = '2';
				break;
			}
			
			b = LEVEL[z][x];
			if (b != ' ') {
				// Hit a block
				//drawCol(ix, iz, b);
				break;
			}
		}
		
		if (b == ' ')
			drawCol(ix, MAX_DEPTH, b);
		else
			drawCol(ix, iz, b);
		
	}
}

void main() __naked {
	char c;
	int move_a;
	int move_z;
	int dx;
	int dz;
	
	// Setup text mode
	//lcd_scroll_cb = NULL;	// Disable auto-scroll
	lcd_x = 0;
	lcd_y = 0;
	
	
	player_x = LEVEL_W / 2;
	player_z = LEVEL_H / 2;
	//for(player_z = 1; player_z < LEVEL_H; player_z++) {
	while(1) {
		
		drawScreen();
		
		c = getchar();
		move_a = 0;
		move_z = 0;
		switch(c) {
			case 'a':
			case 'A':
			#ifdef KEY_CURSOR_LEFT
			case KEY_CURSOR_LEFT:
			#endif
			#ifdef KEY_LEFT
			case KEY_LEFT:
			#endif
				move_a = -1;
				break;
			case 'd':
			case 'D':
			#ifdef KEY_CURSOR_RIGHT
			case KEY_CURSOR_RIGHT:
			#endif
			#ifdef KEY_RIGHT
			case KEY_RIGHT:
			#endif
				move_a = 1;
				break;
			
			case 'w':
			case 'W':
			#ifdef KEY_UP
			case KEY_UP:
			#endif
				//@TODO: sin table
				//player_x += ...
				//player_z --;
				move_z = 1;
				break;
			case 's':
			case 'S':
			#ifdef KEY_DOWN
			case KEY_DOWN:
			#endif
				//@TODO: sin table
				//player_x += ...
				//player_z ++;
				move_z = -1;
				break;
		}
		
		if ((move_a != 0) || (move_z != 0)) {
			player_a = (player_a + (move_a * SPEED_TURN) + SINTABLE_SIZE) % SINTABLE_SIZE;
			
			dx = sin(player_a);
			dz = cos(player_a);
			player_x += (move_z * dx * SPEED_MOVE * OVERSAMPLE) / SINTABLE_SCALE;
			player_z += (move_z * dz * SPEED_MOVE * OVERSAMPLE) / SINTABLE_SCALE;
		}
		
	}
	
	
	//while(1) { }
}
