#ifndef __AGI_COMMANDS_C__
#define __AGI_COMMANDS_C__

/*
 *  AGI Commands
* Based on GBAGI: The Game Boy Advance Adventure Game Interpreter
 *  Copyright (C) 2003,2004 Brian Provinciano, http://www.bripro.com
 * For details: https://github.com/Davidebyzero/GBAGI.git
*/

#include "agi_commands.h"
//#include "gbagi.h"
//#include "commands.h"

#ifdef AGI_COMMANDS_NO_NAMES
	// Safe space (no names)
	#define DEF_AGI_COMMAND(name, func, params, flags) {func, params, flags}
#else
	// Normal:
	#define DEF_AGI_COMMAND(name, func, params, flags) {name, func, params, flags}
#endif

const AGITEST testCommands[MAX_TESTCMD] = {
	DEF_AGI_COMMAND("eval.z", cEvalZ, 0, 0x00),
	DEF_AGI_COMMAND("equaln", cEqualn, 2, 0x80),
	DEF_AGI_COMMAND("equalv", cEqualv, 2, 0xC0),
	DEF_AGI_COMMAND("lessn", cLessn, 2, 0x80),
	DEF_AGI_COMMAND("lessv", cLessv, 2, 0xC0),
	DEF_AGI_COMMAND("greatern", cGreatern, 2, 0x80),
	DEF_AGI_COMMAND("greaterv", cGreaterv, 2, 0xC0),
	DEF_AGI_COMMAND("isset", cIsset, 1, 0x00),
	DEF_AGI_COMMAND("issetv", cIssetv, 1, 0x80),
	DEF_AGI_COMMAND("has", cHas, 1, 0x00),
	DEF_AGI_COMMAND("obj.in.room", cObjInRoom, 2, 0x40),
	DEF_AGI_COMMAND("posn", cPosn, 5, 0x00),
	DEF_AGI_COMMAND("controller", cController, 1, 0x00),
	DEF_AGI_COMMAND("have.key", cHaveKey, 0, 0x00),
	DEF_AGI_COMMAND("said", cSaid, 0, 0x00),
	DEF_AGI_COMMAND("compare.strings", cCompareStrings, 2, 0x00),
	DEF_AGI_COMMAND("obj.in.box", cObjInBox, 5, 0x00),
	DEF_AGI_COMMAND("center.posn", cCenterPosn, 5, 0x00),
	DEF_AGI_COMMAND("right.posn", cRightPosn, 5, 0x00),
};

const AGICMD agiCommands[MAX_AGICMD] = {
	DEF_AGI_COMMAND("return", cReturn, 0, 0x00),
	DEF_AGI_COMMAND("increment", cIncrement, 1, 0x80),
	DEF_AGI_COMMAND("decrement", cDecrement, 1, 0x80),
	DEF_AGI_COMMAND("assignn", cAssignn, 2, 0x80),
	DEF_AGI_COMMAND("assignv", cAssignv, 2, 0xC0),
	DEF_AGI_COMMAND("addn", cAddn, 2, 0x80),
	DEF_AGI_COMMAND("addv", cAddv, 2, 0xC0),
	DEF_AGI_COMMAND("subn", cSubn, 2, 0x80),
	DEF_AGI_COMMAND("subv", cSubv, 2, 0xC0),
	DEF_AGI_COMMAND("lindirectv", cLindirectv, 2, 0xC0),
	DEF_AGI_COMMAND("rindirect", cRindirect, 2, 0xC0),
	DEF_AGI_COMMAND("lindirectn", cLindirectn, 2, 0x80),
	DEF_AGI_COMMAND("set", cSet, 1, 0x00),
	DEF_AGI_COMMAND("reset", cReset, 1, 0x00),
	DEF_AGI_COMMAND("toggle", cToggle, 1, 0x00),
	DEF_AGI_COMMAND("set.v", cSetV, 1, 0x80),
	DEF_AGI_COMMAND("reset.v", cResetV, 1, 0x80),
	DEF_AGI_COMMAND("toggle.v", cToggleV, 1, 0x80),
	DEF_AGI_COMMAND("new.room", cNewRoom, 1, 0x00),
	DEF_AGI_COMMAND("new.room.v", cNewRoomV, 1, 0x80),
	DEF_AGI_COMMAND("load.logics", cLoadLogics, 1, 0x00),
	DEF_AGI_COMMAND("load.logics.v", cLoadLogicsV, 1, 0x80),
	DEF_AGI_COMMAND("call", cCall, 1, 0x00),
	DEF_AGI_COMMAND("call.v", cCallV, 1, 0x80),
	DEF_AGI_COMMAND("load.pic", cLoadPic, 1, 0x80),
	DEF_AGI_COMMAND("draw.pic", cDrawPic, 1, 0x80),
	DEF_AGI_COMMAND("show.pic", cShowPic, 0, 0x00),
	DEF_AGI_COMMAND("discard.pic", cDiscardPic, 1, 0x80),
	DEF_AGI_COMMAND("overlay.pic", cOverlayPic, 1, 0x80),
	DEF_AGI_COMMAND("show.pri.screen", cShowPriScreen, 0, 0x00),
	DEF_AGI_COMMAND("load.view", cLoadView, 1, 0x00),
	DEF_AGI_COMMAND("load.view.v", cLoadViewV, 1, 0x80),
	DEF_AGI_COMMAND("discard.view", cDiscardView, 1, 0x00),
	DEF_AGI_COMMAND("animate.obj", cAnimateObj, 1, 0x00),
	DEF_AGI_COMMAND("unanimate.all", cUnanimateAll, 0, 0x00),
	DEF_AGI_COMMAND("draw", cDraw, 1, 0x00),
	DEF_AGI_COMMAND("erase", cErase, 1, 0x00),
	DEF_AGI_COMMAND("position", cPosition, 3, 0x00),
	DEF_AGI_COMMAND("position.v", cPositionV, 3, 0x60),
	DEF_AGI_COMMAND("get.posn", cGetPosn, 3, 0x60),
	DEF_AGI_COMMAND("reposition", cReposition, 3, 0x60),
	DEF_AGI_COMMAND("set.view", cSetView, 2, 0x00),
	DEF_AGI_COMMAND("set.view.v", cSetViewV, 2, 0x40),
	DEF_AGI_COMMAND("set.loop", cSetLoop, 2, 0x00),
	DEF_AGI_COMMAND("set.loop.v", cSetLoopV, 2, 0x40),
	DEF_AGI_COMMAND("fix.loop", cFixLoop, 1, 0x00),
	DEF_AGI_COMMAND("release.loop", cReleaseLoop, 1, 0x00),
	DEF_AGI_COMMAND("set.cel", cSetCel, 2, 0x00),
	DEF_AGI_COMMAND("set.cel.v", cSetCelV, 2, 0x40),
	DEF_AGI_COMMAND("last.cel", cLastCel, 2, 0x40),
	DEF_AGI_COMMAND("current.cel", cCurrentCel, 2, 0x40),
	DEF_AGI_COMMAND("current.loop", cCurrentLoop, 2, 0x40),
	DEF_AGI_COMMAND("current.view", cCurrentView, 2, 0x40),
	DEF_AGI_COMMAND("number.of.loops", cNumberOfLoops, 2, 0x40),
	DEF_AGI_COMMAND("set.priority", cSetPriority, 2, 0x00),
	DEF_AGI_COMMAND("set.priority.v", cSetPriorityV, 2, 0x40),
	DEF_AGI_COMMAND("release.priority", cReleasePriority, 1, 0x00),
	DEF_AGI_COMMAND("get.priority", cGetPriority, 2, 0x40),
	DEF_AGI_COMMAND("stop.update", cStopUpdate, 1, 0x00),
	DEF_AGI_COMMAND("start.update", cStartUpdate, 1, 0x00),
	DEF_AGI_COMMAND("force.update", cForceUpdate, 1, 0x00),
	DEF_AGI_COMMAND("ignore.horizon", cIgnoreHorizon, 1, 0x00),
	DEF_AGI_COMMAND("observe.horizon", cObserveHorizon, 1, 0x00),
	DEF_AGI_COMMAND("set.horizon", cSetHorizon, 1, 0x00),
	DEF_AGI_COMMAND("object.on.water", cObjectOnWater, 1, 0x00),
	DEF_AGI_COMMAND("object.on.land", cObjectOnLand, 1, 0x00),
	DEF_AGI_COMMAND("object.on.anything", cObjectOnAnything, 1, 0x00),
	DEF_AGI_COMMAND("ignore.objs", cIgnoreObjs, 1, 0x00),
	DEF_AGI_COMMAND("observe.objs", cObserveObjs, 1, 0x00),
	DEF_AGI_COMMAND("distance", cDistance, 3, 0x20),
	DEF_AGI_COMMAND("stop.cycling", cStopCycling, 1, 0x00),
	DEF_AGI_COMMAND("start.cycling", cStartCycling, 1, 0x00),
	DEF_AGI_COMMAND("normal.cycle", cNormalCycle, 1, 0x00),
	DEF_AGI_COMMAND("end.of.loop", cEndOfLoop, 2, 0x00),
	DEF_AGI_COMMAND("reverse.cycle", cReverseCycle, 1, 0x00),
	DEF_AGI_COMMAND("reverse.loop", cReverseLoop, 2, 0x00),
	DEF_AGI_COMMAND("cycle.time", cCycleTime, 2, 0x40),
	DEF_AGI_COMMAND("stop.motion", cStopMotion, 1, 0x00),
	DEF_AGI_COMMAND("start.motion", cStartMotion, 1, 0x00),
	DEF_AGI_COMMAND("step.size", cStepSize, 2, 0x40),
	DEF_AGI_COMMAND("step.time", cStepTime, 2, 0x40),
	DEF_AGI_COMMAND("move.obj", cMoveObj, 5, 0x00),
	DEF_AGI_COMMAND("move.obj.v", cMoveObjV, 5, 0x70),
	DEF_AGI_COMMAND("follow.ego", cFollowEgo, 3, 0x00),
	DEF_AGI_COMMAND("wander", cWander, 1, 0x00),
	DEF_AGI_COMMAND("normal.motion", cNormalMotion, 1, 0x00),
	DEF_AGI_COMMAND("set.dir", cSetDir, 2, 0x40),
	DEF_AGI_COMMAND("get.dir", cGetDir, 2, 0x40),
	DEF_AGI_COMMAND("ignore.blocks", cIgnoreBlocks, 1, 0x00),
	DEF_AGI_COMMAND("observe.blocks", cObserveBlocks, 1, 0x00),
	DEF_AGI_COMMAND("block", cBlock, 4, 0x00),
	DEF_AGI_COMMAND("unblock", cUnblock, 0, 0x00),
	DEF_AGI_COMMAND("get", cGet, 1, 0x00),
	DEF_AGI_COMMAND("get.v", cGetV, 1, 0x80),
	DEF_AGI_COMMAND("drop", cDrop, 1, 0x00),
	DEF_AGI_COMMAND("put", cPut, 2, 0x00),
	DEF_AGI_COMMAND("put.v", cPutV, 2, 0x40),
	DEF_AGI_COMMAND("get.room.v", cGetRoomV, 2, 0xC0),
	DEF_AGI_COMMAND("load.sound", cLoadSound, 1, 0x00),
	DEF_AGI_COMMAND("sound", cSound, 2, 0x00),
	DEF_AGI_COMMAND("stop.sound", cStopSound, 0, 0x00),
	DEF_AGI_COMMAND("print", cPrint, 1, 0x00),
	DEF_AGI_COMMAND("print.v", cPrintV, 1, 0x80),
	DEF_AGI_COMMAND("display", cDisplay, 3, 0x00),
	DEF_AGI_COMMAND("display.v", cDisplayV, 3, 0xE0),
	DEF_AGI_COMMAND("clear.lines", cClearLines, 3, 0x00),
	DEF_AGI_COMMAND("text.screen", cTextScreen, 0, 0x00),
	DEF_AGI_COMMAND("graphics", cGraphics, 0, 0x00),
	DEF_AGI_COMMAND("set.cursor.char", cSetCursorChar, 1, 0x00),
	DEF_AGI_COMMAND("set.text.attribute", cSetTextAttribute, 2, 0x00),
	DEF_AGI_COMMAND("shake.screen", cShakeScreen, 1, 0x00),
	DEF_AGI_COMMAND("configure.screen", cConfigureScreen, 3, 0x00),
	DEF_AGI_COMMAND("status.line.on", cStatusLineOn, 0, 0x00),
	DEF_AGI_COMMAND("status.line.off", cStatusLineOff, 0, 0x00),
	DEF_AGI_COMMAND("set.string", cSetString, 2, 0x00),
	DEF_AGI_COMMAND("get.string", cGetString, 5, 0x00),
	DEF_AGI_COMMAND("word.to.string", cWordToString, 2, 0x00),
	DEF_AGI_COMMAND("parse", cParse, 1, 0x00),
	DEF_AGI_COMMAND("get.num", cGetNum, 2, 0x40),
	DEF_AGI_COMMAND("prevent.input", cPreventInput, 0, 0x00),
	DEF_AGI_COMMAND("accept.input", cAcceptInput, 0, 0x00),
	DEF_AGI_COMMAND("set.key", cSetKey, 3, 0x00),
	DEF_AGI_COMMAND("add.to.pic", cAddToPic, 7, 0x00),
	DEF_AGI_COMMAND("add.to.pic.v", cAddToPicV, 7, 0xFE),
	DEF_AGI_COMMAND("status", cStatus, 0, 0x00),
	DEF_AGI_COMMAND("save.game", cSaveGame, 0, 0x00),
	DEF_AGI_COMMAND("restore.game", cRestoreGame, 0, 0x00),
	DEF_AGI_COMMAND("init.disk", cInitDisk, 0, 0x00),
	DEF_AGI_COMMAND("restart.game", cRestartGame, 0, 0x00),
	DEF_AGI_COMMAND("show.obj", cShowObj, 1, 0x00),
	DEF_AGI_COMMAND("random", cRandom, 3, 0x20),
	DEF_AGI_COMMAND("program.control", cProgramControl, 0, 0x00),
	DEF_AGI_COMMAND("player.control", cPlayerControl, 0, 0x00),
	DEF_AGI_COMMAND("obj.status.v", cObjStatusV, 1, 0x80),
	DEF_AGI_COMMAND("quit", cQuit, 1, 0x00),
	DEF_AGI_COMMAND("show.mem", cShowMem, 0, 0x00),
	DEF_AGI_COMMAND("pause", cPause, 0, 0x00),
	DEF_AGI_COMMAND("echo.line", cEchoLine, 0, 0x00),
	DEF_AGI_COMMAND("cancel.line", cCancelLine, 0, 0x00),
	DEF_AGI_COMMAND("init.joy", cInitJoy, 0, 0x00),
	DEF_AGI_COMMAND("toggle.monitor", cToggleMonitor, 0, 0x00),
	DEF_AGI_COMMAND("version", cVersion, 0, 0x00),
	DEF_AGI_COMMAND("script.size", cScriptSize, 1, 0x00),
	DEF_AGI_COMMAND("set.game.id", cSetGameId, 1, 0x00),
	DEF_AGI_COMMAND("log", cLog, 1, 0x00),
	DEF_AGI_COMMAND("set.scan.start", cSetScanStart, 0, 0x00),
	DEF_AGI_COMMAND("reset.scan.start", cResetScanStart, 0, 0x00),
	DEF_AGI_COMMAND("reposition.to", cRepositionTo, 3, 0x00),
	DEF_AGI_COMMAND("reposition.to.v", cRepositionToV, 3, 0x60),
	DEF_AGI_COMMAND("trace.on", cTraceOn, 0, 0x00),
	DEF_AGI_COMMAND("trace.info", cTraceInfo, 3, 0x00),
	DEF_AGI_COMMAND("print.at", cPrintAt, 4, 0x00),
	DEF_AGI_COMMAND("print.at.v", cPrintAtV, 4, 0x80),
	DEF_AGI_COMMAND("discard.view.v", cDiscardViewV, 1, 0x80),
	DEF_AGI_COMMAND("clear.text.rect", cClearTextRect, 5, 0x00),
	DEF_AGI_COMMAND("set.upper.left", cSetUpperLeft, 2, 0x00),
	DEF_AGI_COMMAND("set.menu", cSetMenu, 1, 0x00),
	DEF_AGI_COMMAND("set.menu.item", cSetMenuItem, 2, 0x00),
	DEF_AGI_COMMAND("submit.menu", cSubmitMenu, 0, 0x00),
	DEF_AGI_COMMAND("enable.item", cEnableItem, 1, 0x00),
	DEF_AGI_COMMAND("disable.item", cDisableItem, 1, 0x00),
	DEF_AGI_COMMAND("menu.input", cMenuInput, 0, 0x00),
	DEF_AGI_COMMAND("show.obj.v", cShowObjV, 1, 0x01),
	DEF_AGI_COMMAND("open.dialogue", cOpenDialogue, 0, 0x00),
	DEF_AGI_COMMAND("close.dialogue", cCloseDialogue, 0, 0x00),
	DEF_AGI_COMMAND("mul.n", cMulN, 2, 0x80),
	DEF_AGI_COMMAND("mul.v", cMulV, 2, 0xC0),
	DEF_AGI_COMMAND("div.n", cDivN, 2, 0x80),
	DEF_AGI_COMMAND("div.v", cDivV, 2, 0xC0),
	DEF_AGI_COMMAND("close.window", cCloseWindow, 0, 0x00),
	DEF_AGI_COMMAND("set.simple", cSetSimple, 1, 0x00),
	DEF_AGI_COMMAND("push.script", cPushScript, 0, 0x00),
	DEF_AGI_COMMAND("pop.script", cPopScript, 0, 0x00),
	DEF_AGI_COMMAND("hold.key", cHoldKey, 0, 0x00),
	DEF_AGI_COMMAND("set.pri.base", cSetPriBase, 1, 0x00),
	DEF_AGI_COMMAND("discard.sound", cDiscardSound, 1, 0x00),
	DEF_AGI_COMMAND("hide.mouse", cHideMouse, 0, 0x00),
	DEF_AGI_COMMAND("allow.menu", cAllowMenu, 1, 0x00),
	DEF_AGI_COMMAND("show.mouse", cShowMouse, 0, 0x00),
	DEF_AGI_COMMAND("fence.mouse", cFenceMouse, 4, 0x00),
	DEF_AGI_COMMAND("cmd.mouse.posn", cMousePosn, 2, 0x00),
	DEF_AGI_COMMAND("cmd.release.key", cReleaseKey, 0, 0x00),
	DEF_AGI_COMMAND("adj.ego.move.to.x.y",cAdjEgoMoveToXY,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND(NULL,InvalidBox,0,0x00),
	DEF_AGI_COMMAND("GOTO",ExecuteGoto,0,0x00),
	DEF_AGI_COMMAND("IF",ExecuteIF,0,0x00)
};




#endif