
#NAME=ports
NAME=app_gl6000sound

# To see the result on serial terminal and recover quickly
#SEND2MONITOR_KEEP_SIO = 1
#SEND2MONITOR_RESET = 1

# For targeting a specific model:
#VGLDK_SERIES = 1000
#VGLDK_SERIES = 2000
#VGLDK_SERIES = 4000
#VGLDK_SERIES = 6000

# For small loadable apps (without their own I/O):
VGLDK_SERIES = 0
LOC_CODE = 0xc400
LOC_DATA = 0xc000

include ../../tools/Makefile.mk

all: cart
