#!/usr/bin/python3
"""
BIN2H
Convert a .h file to be used for static testing
2020-09-06 Bernhard "HotKey" Slawik
"""

import sys
import os

def put(t):
	print(str(t))

if __name__ == '__main__':
	
	if len(sys.argv) < 3:
		put('Usage: %s [filename.bin] [filename.h]' % __file__)
		put(__doc__)
		sys.exit(1)
	
	filename_in = sys.argv[1]
	filename_out = sys.argv[2]
	
	data_name = os.path.basename(filename_in)
	data_name = data_name.split('.')[0]
	data_name = data_name.upper()
	data_name = data_name.replace('.', '_')
	
	write_define = True	# Write a "#define" or a variable?
	
	r = ''
	r += '/*\n'
	r += '	Auto-generated by %s\n' % (__file__)
	r += '	Source: %s\n' % filename_in
	r += '*/\n'
	r += '\n'
	
	with open(filename_in, 'rb') as h:
		data = h.read()
	
	r += '#define %s_LEN %d\n' % (data_name, len(data))
	
	
	if (write_define):
		# Write as define
		r += '#define %s_DATA {' % (data_name)
	else:
		# Write as variable
		#r += 'unsigned char %s[%d] = {' % (data_name, len(data))
		r += 'unsigned char %s_DATA[%s_LEN] = {' % (data_name, data_name)
	
	COLS = 16
	i = 0
	for b in data:
		if (i > 0): r += ','
		
		if (i % COLS == 0):
			if (write_define):
				r += '\\'
			r += '\n'
			r += '\t'
		
		r += '0x%02x' % b
		i += 1
	if (write_define):
		r += '\\\n'
		r += '}\n'
	else:
		r += '\n'
		r += '};\n'
	
	
	put('Writing "%s"...' % filename_out)
	with open(filename_out, 'w') as h:
		h.write(r)
	