
NAME = hello

# For targeting a specific model:
#VGLDK_SERIES = 1000
#VGLDK_SERIES = 2000
#VGLDK_SERIES = 4000
#VGLDK_SERIES = 6000

# For small loadable apps (without their own I/O):
VGLDK_SERIES = 0
LOC_CODE = 0xc200
LOC_DATA = 0xc000

all: upload
#all: app
#all: cart
#all: emu

include ../../tools/Makefile.mk

