
#NAME = app_hello
#NAME = app_tests
#NAME = app_cserial
NAME = app_gl6000sound

# For targeting a specific model:
#VGLDK_SERIES = 1000
#VGLDK_SERIES = 2000
#VGLDK_SERIES = 4000
#VGLDK_SERIES = 6000

# For small loadable apps (without their own I/O):
VGLDK_SERIES = 0
LOC_CODE = 0xc800
#LOC_DATA = 0xe000
LOC_DATA = 0xc000

all: upload
#all: app
#all: cart
#all: emu

include ../../tools/Makefile.mk

