
NAME=monitor

#VGLDK_SERIES=1000
#VGLDK_SERIES=2000
VGLDK_SERIES=4000
#VGLDK_SERIES=6000

# Only use upper memory bank?
LOC_CODE=0x8000
#LOC_DATA=0xc020
LOC_DATA=0xd000

CART_SIZE_KB=8
#CART_SIZE_KB=16

include ../../tools/Makefile.mk

all: cart
